# pv-definition.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/data
  # or create AWS volume
  # awsElasticBlockStore:
  # volumeID: <volume-id>
  # fsType: ext4
# kubectl create -f pv-defintion.yaml
# kubectl get persistentvolume
