apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 3
  serviceName: mysql-h
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
  #         ports:
  #           - containerPort: 3306
  #         env:
  #           - name: MYSQL_ROOT_PASSWORD
  #             value: "password"
  # volumeClaimTemplates:
  #   - metadata:
  #       name: mysql-pvc
  #     spec:
  #       accessModes: ["ReadWriteOnce"]
  #       resources:
  #         requests:
  #           storage: 1Gi
