apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
type: Opaque
data:
  root-password: <base64-encoded-root-password>
  app-user: <base64-encoded-app-user>
  app-password: <base64-encoded-app-password>
