apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: front-end
spec:
  containers: # can have multiple containers [list/array]
    - name: nginx-container # dictionary
      image: nginx
