apiVersion: v1
kind: ReplicationController
metadata: # Replication controller
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata: # pod
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
